# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'rabdulsalaam@gmail.com'
  config.password       = 'rashad1980'
  config.integrator_key = 'HAPP-84e73953-a0eb-482f-9b07-73d7bb014375'
  config.account_id     = '233485'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

